export const SET_PLAYER_STATS_STATUS = 'SET_PLAYER_STATS_STATUS'
export const GET_PLAYER_STATS = 'GET_PLAYER_STATS'
export const SET_PLAYER_STATS = 'SET_PLAYER_STATS'
export const REQUEST_NEW_PLAYER_STATS_AGGREGATION = 'REQUEST_NEW_PLAYER_STATS_AGGREGATION'
