import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Http, BaseRequestOptions } from '@angular/http';
import { MockBackend } from '@angular/http/testing';
import { MockBackendService } from './mock-backend/mock-backend-error';

/**
 * This module sets up the environment for unit testing that returns no data from any http request. It does this by
 * providing the mock-backend.service which intercepts the http calls
 * that are generated by the unit tests supplying mock responses.
 */
@NgModule({
    imports: [
        CommonModule
    ],
    declarations: [],
    providers: [
        BaseRequestOptions,
        MockBackend,
        {
            provide: Http,
            deps: [MockBackend, BaseRequestOptions],
            useFactory: new MockBackendService().mockBackendImpl
        }
    ]
})
export class TestModule {}
