export const ATTEMPTING_SINGING_IN = 'ATTEMPTING_SINGING_IN'
export const ATTEMPTING_SINGING_OUT = 'ATTEMPTING_SINGING_OUT'
export const SIGNED_IN = 'SIGNED_IN'
export const SIGNED_OUT = 'SIGNED_OUT'
