export const CHANGE_AGGREGATION = 'CHANGE_AGGREGATION'

export const GET_PLAYER_STATS = 'GET_PLAYER_STATS'
export const SET_PLAYER_STATS = 'SET_PLAYER_STATS'
export const SET_PLAYER_STATS_ERROR = 'SET_PLAYER_STATS_ERROR'
